### ISSUE TITLE
Please give an example of using zingchart-react with drilldown feature.

### ISSUE THREAD

**Issue by duongthienlee** [zingchart-demos/react#1]
As I mentioned on the title. So far, I haven't figure out the way to do that. I can only manage to drill-down forwards, when I click the Shape, it should render the chart with originalConfig 
    `                 zingchart.render({
                        id: 'myChart',
                        data: oriConfig,
                        height: '100%',
                        width: '100%'
                    });`
But we are using React, how can we trigger the render() in React ?
My solution is that I add another drilldownDataStructure[originalConfig], then
    `zingchart.bind(null, 'shape_click', (p) => {
          var shapeId = p.shapeid;
          zingchart.exec('myChart', 'setseriesdata', {
              data: drilldownDataStructure[['or']]['series']
            });
        })`

**Comment by damntrecky** [comment]
Hi Thien,

Based on your site, it seems you have already got drilldown in react working no?

https://thienwinchester.netlify.com/

![Screen Recording 2019-05-06 at 09 18 AM](https://user-images.githubusercontent.com/38665452/57239235-2aa00b80-6fe0-11e9-8bb0-e668aeda33ac.gif)

**Comment by duongthienlee** [comment]
Oh yes, I've already found a solution for it. Thank you anyways
